"use client";

import { Inter, Plus_Jakarta_Sans } from "next/font/google";
import { Navbar, Aside } from "./components/UI";
import { useState } from "react";
import { PrimeReactProvider } from "primereact/api";
import { usePathname } from "next/navigation";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"] });

// export const metadata = {
//   title: "Notulensi Rapat",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathName = usePathname();
  const [isSidebar, setIsSidebar] = useState(false);
  const handleSidebar = () => {
    setIsSidebar(true);
  };
  return (
    <html lang="en">
      <body className={jakarta.className}>
        <PrimeReactProvider>
          <Navbar handleSidebar={handleSidebar} />
          {isSidebar && <Aside isSidebar={isSidebar} pathName={pathName} />}
          {children}
        </PrimeReactProvider>
      </body>
    </html>
  );
}
